### PR TITLE
use versioneer for versioning

### LINKED ISSUE #35: use versioneer
https://github.com/warner/python-versioneer - convenient way to keep track of versions.

I suggest we use the simple tag/release scheme: MAJOR.MINOR.PATCH (so the tags marking releases will just be `0.1.0`, `0.5.1`, `1.0.0` etc.

(same as for gridDataFormats, see https://github.com/MDAnalysis/GridDataFormats/wiki/Developer-Guide#release-management )

### PR DESCRIPTION
**Pull request by orbeckst**
Fixes #35 

Changes made in this Pull Request:
- use tag MAJOR.MINOR.PATCH to set releases
- added DeveloperGuide at https://github.com/MDAnalysis/pmda/wiki/Developer-Guide
  to document the procedure
- updated setup.py with metadata in preparation for a release #32

PR Checklist
------------
 - [x] Tests?
 - [x] Docs? – wiki [Developer Guide](https://github.com/MDAnalysis/pmda/wiki/Developer-Guide)
 - [ ] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by kain88-de** [comment]
where do we specify the version?

**Comment by orbeckst** [comment]
> where do we specify the version?

You tag with
```
git tag -m 'release 0.1.0' 0.1.0
git push --tags
git push
```
That's all. See pmda wiki [Release management](https://github.com/MDAnalysis/pmda/wiki/Developer-Guide#release-management)

**Comment by kain88-de** [comment]
Oh great. @orbeckst you need to remove the version files from the coverage report (- 25% that is enourmous)

**Comment by orbeckst** [comment]
The nice thing is that it automatically generates versions that show what you're building beyond a release .using [PEP440](https://www.python.org/dev/peps/pep-0440/).

**Comment by orbeckst** [comment]
coverage: yes, just pushed update.

**Comment by orbeckst** [comment]
Pylint fails. How can I exclude `_version.py`?

**Comment by orbeckst** [comment]
I managed to exclude `_version.py` by adding an omit line that **starts with `*`** (even though it is not clear from the docs [specifying source files in coverage](https://coverage.readthedocs.io/en/coverage-4.2/source.html#source) that this would be necessary):
```ini
[run]
branch = True
omit =
    # omit all tests
    */pmda/test/*
    # omit the versioneer-installed _version.py
    */pmda/_version.py
```

Just `pmda/_version.py` *should* have worked, I think (but it didn't).

**Pull request merged**
