### PR TITLE
modify the names of schedulers

### LINKED ISSUE #102: check scheduler names
We set the `compute()` scheduler near https://github.com/MDAnalysis/pmda/blob/34d465b06a8370394e3cb7fc6c4394116614666d/pmda/parallel.py#L332-L337 as
- "multiprocessing"
- assume single threaded if n_jobs=1
- Client (from distributed)

However, in Dask 2.1+ https://docs.dask.org/en/latest/scheduling.html we should use
- "processing"
- "synchronous"

We need to check that setting the scheduler in PMDA to multiprocessing or single-threaded still works.

Check the versions of dask and their changelog – did they change the names at some time? If so, require a minimal version of dask...

This is also important for testing of schedulers in https://github.com/MDAnalysis/pmda/blob/34d465b06a8370394e3cb7fc6c4394116614666d/conftest.py#L28-L37

### PR DESCRIPTION
**Pull request by VOD555**
Fixes #102 

Changes made in this Pull Request:
 - Modify the names of schedulers:
    multiporcessing --> processes
    single-threaded --> synchronous
    threaded --> threads

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Comment by orbeckst** [comment]
Still errors – do the docs build locally?

**Comment by VOD555** [comment]
They didn't change the scheduler name on the debugging page https://docs.dask.org/en/latest/debugging.html#use-the-single-threaded-scheduler.

**Comment by orbeckst** [comment]
Did you test that the new name worked? (Maybe the old one also works...?)

**Comment by VOD555** [comment]
> Did you test that the new name worked? (Maybe the old one also works...?)

My local tests showed that both the old names and the new names worked.

**Pull request merged**
