### PR TITLE
add code coverage

### PR DESCRIPTION
**Pull request by kain88-de**
add code coverage

### CODE REVIEW

**Comment by orbeckst** [comment]
... just add a "yes" (in principle) so that you can merge when it works.

**Comment by orbeckst** [comment]
Fails with
```
pytest: error: unrecognized arguments: --cov pmda
```

???

**Comment by kain88-de** [comment]
yeah I'm on it. Slight misconfiguration

**Comment by kain88-de** [comment]
The ci-helper should install pytest-coverage but it only does so when I put speficic parts of the pytest command in the variable `SETUP_CMD`.

**Comment by orbeckst** [comment]
Can you add a badge to the README?

**Pull request merged**
